library(shiny)
library(shinydashboard)
library(DT)
library(dbplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)

nassau = read.csv('./data/nassau.csv',stringsAsFactors = FALSE)
nassau = nassau %>% mutate(.,Sold = as.Date(Sold))
str(nassau)
unique(nassau$Bedrooms)
town_names = sort(unique(nassau$Town))
design = append(sort(unique(nassau$DesignType)),'All',after = 0)
number_bedrooms = sort(unique(nassau$Bedrooms))
maxprice = max(nassau$SoldPrice)
minprice = min(nassau$SoldPrice)
yearsDOM = append(sort(unique(nassau$Year)),'All',after = 0)
yearscontract = append(sort(unique(nassau$Year)),'All',after = 0)

