library(shiny)
library(shinydashboard)
library(DT)
library(dbplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)

nassau = read.csv('./data/nassau.csv',stringsAsFactors = FALSE)
nassau = nassau %>% mutate(.,Sold = as.Date(Sold)) %>% filter(.,Town != "Plandome Manor")
nassau$DaysOnMarket = ifelse(is.na(nassau$DaysOnMarket), 65,nassau$DaysOnMarket)
nassau = nassau %>% mutate(.,Bedrooms_cat = Bedrooms) 
nassau$Bedrooms_cat = ifelse(nassau$Bedrooms_cat > 5, '5+',nassau$Bedrooms_cat)
sort(unique(nassau$Bedrooms_cat))
nassau =nassau %>% mutate(.,Month = as.numeric(substr(SellYM,6,7)))
str(nassau)
unique(nassau$Bedrooms)
town_names = sort(unique(nassau$Town))
design = append(sort(unique(nassau$DesignType)),'All',after = 0)
number_bedrooms = sort(unique(nassau$Bedrooms))
maxprice = max(nassau$SoldPrice)
minprice = min(nassau$SoldPrice)
yearsDOM = append(sort(unique(nassau$Year)),'All',after = 0)
yearscontract = append(sort(unique(nassau$Year)),'All',after = 0)
top_town=c('Hempstead','Levittown','Freeport','Westbury','Oceanside','Plainview','Great Neck')
disctrict_names = sort(unique(nassau$SD))
contracts_saleprice = c('Average Price of Home Sold','Number of Homes Sold')